import type { RecommendationReport } from "./recommend.js";
import type { BacktestReport } from "./backtest.js";

const percent = (value: number | null): string =>
  value === null ? "n/a" : `${(value * 100).toFixed(1)}%`;

const seconds = (value: number | null): string =>
  value === null ? "n/a" : `${value.toFixed(1)}s`;

export function formatActionReport(
  repository: string,
  workflow: string | undefined,
  recommendation: RecommendationReport,
  backtest: BacktestReport | null,
  backtestError?: string,
): string {
  const selected = recommendation.selectedCells
    .map((cell) => `- \`${cell.cell}\` — failures=${cell.coveredFailures}, combinations=${cell.coveredCombinations}, median=${seconds(cell.medianRuntimeSeconds)}`)
    .join("\n");

  const historical = recommendation.historicalRecall === null
    ? "n/a (no analyzed failure fingerprints)"
    : `${recommendation.coveredFingerprints}/${recommendation.historicalFingerprints} (${percent(recommendation.historicalRecall)})`;

  const combinatorial = recommendation.combinatorialCoverage === null
    ? "n/a"
    : `${recommendation.coveredCombinatorialRequirements}/${recommendation.combinatorialRequirements} (${percent(recommendation.combinatorialCoverage)})`;

  const reduction = recommendation.estimatedComputeReductionPercent === null
    ? "n/a"
    : `${recommendation.estimatedComputeReductionPercent.toFixed(1)}%`;

  const backtestRows = backtest
    ? [
        `| Holdout failure recall | ${backtest.coveredHoldoutFingerprints}/${backtest.holdoutFingerprints} (${percent(backtest.holdoutRecall)}) |`,
        `| Unseen-failure recall | ${backtest.unseenHoldoutRecall === null ? "n/a" : `${backtest.coveredUnseenHoldoutFingerprints}/${backtest.unseenHoldoutFingerprints} (${percent(backtest.unseenHoldoutRecall)})`} |`,
        `| Holdout combinatorial coverage | ${backtest.holdoutCombinatorialCoverage === null ? "n/a" : `${backtest.coveredHoldoutCombinatorialRequirements}/${backtest.holdoutCombinatorialRequirements} (${percent(backtest.holdoutCombinatorialCoverage)})`} |`,
      ].join("\n")
    : `| Backtest | unavailable${backtestError ? `: ${backtestError}` : ""} |`;

  const warnings = recommendation.warnings
    .map((warning) => `- ⚠️ ${warning}`)
    .join("\n");

  return `<!-- matrixtrim-report -->
## MatrixTrim analysis

**Repository:** \`${repository}\`  
**Workflow:** \`${workflow ?? "all"}\`  
**Coverage strength:** ${recommendation.coverageStrength}

| Metric | Result |
| --- | ---: |
| Current matrix cells | ${recommendation.currentCells} |
| Suggested cells | ${recommendation.selectedCells.length} |
| Historical failure recall | ${historical} |
| Observed combinatorial coverage | ${combinatorial} |
| Estimated compute | ${seconds(recommendation.currentEstimatedSeconds)} → ${seconds(recommendation.selectedEstimatedSeconds)} |
| Estimated compute reduction | ${reduction} |
${backtestRows}

<details>
<summary>Suggested cells</summary>

${selected || "_No cells selected._"}

</details>

### Interpretation

MatrixTrim measures the historical failure-detection value of CI configurations. A recommendation is **evidence, not proof that removed configurations can never catch a future failure**.

${warnings}

_Generated by MatrixTrim._
`;
}
